update fortISSimO.asm
ISSOtm/fortISSimO pull request #23
Opened 2024-09-01 10:28 UTC by MrBlinky

optimize hUGE_SelectSong

2024-09-01 13:21 UTC, ISSOtm requested changes
Thank you! I would just like a small stylistic change.

2024-09-01 13:21 UTC, ISSOtm commented on fortISSimO.asm
> +	ld l,rNR22 & $FF
```suggestion
	ld l, LOW(rNR22)
```

2024-09-01 13:21 UTC, ISSOtm commented on fortISSimO.asm
> +	ld l, rNR30 & $FF
```suggestion
	ld l, LOW(rNR30)
```

2024-09-01 13:21 UTC, ISSOtm commented on fortISSimO.asm
> +	ld l,rNR42 & $FF
```suggestion
	ld l, LOW(rNR42)
```

2024-09-01 18:13 UTC, MrBlinky commented
Looks much better. Updated

2024-09-02 16:25 UTC, ISSOtm approved these changes
Thank you!

2024-09-02 16:28 UTC, merged